Feature/exo 4676 add support generic typeform
exolever/django-typeform-feedback pull request #4
Opened 2019-09-25 13:22 UTC by jsujar

## Problem

Add support for Generics typeforms

## Solution

I've craeted a mixin to support acces to this new feature and a new webhook to process this typeform responses.

## Commandments

- [ ] Write PEP8 compliant code.
- [ ] Cover it with tests.
- [ ] Pay attention to backward compatibility, or if it breaks it, explain why.
- [ ] Update documentation (if relevant).

2019-09-25 13:57 UTC, tomasgarzon requested changes

2019-09-25 13:57 UTC, tomasgarzon commented on typeform_feedback/mixin.py
> +    def get_user_answers(self, user_uuid, typeform_id):
aquí debemos usar el user pk, ya que el uuid no es algo estandar en los usuarios de django.

2019-09-25 13:57 UTC, tomasgarzon commented on typeform_feedback/models.py
> +        blank=True,     # Remove
estos comentarios los podemos borrar, no?

2019-09-25 13:57 UTC, tomasgarzon commented on typeform_feedback/tasks.py
> +    pass
esta linea creo que ya sobra

2019-09-25 13:57 UTC, tomasgarzon commented on typeform_feedback/tasks.py
> +from typeform.tasks import TypeformWebhookMixin
esta aplicacion typeform donde está definida? no veo su codigo en el repo ni una app externa

2019-09-25 14:01 UTC, jsujar commented on typeform_feedback/tasks.py
> +from typeform.tasks import TypeformWebhookMixin
Esto si es un error, debería ser .tasks

2019-09-25 14:32 UTC, jsujar commented on typeform_feedback/mixin.py
> +    def get_user_answers(self, user_uuid, typeform_id):
Totalmente de acuerdo.

2019-09-26 06:52 UTC, marfyl commented
habria que revisar el coverage, ha bajado un -27.57%

2019-09-26 06:53 UTC, marfyl commented on requirements_dev.txt
> +
es necesario añadirlos aqui de nuevo? estas dependencias estan ya en el setup.py

2019-09-26 07:51 UTC, jsujar commented on requirements_dev.txt
> +
Setup.py se ejecuta cuando se está inslando el paquete.

2019-10-02 10:31 UTC, closed without merging